name: Tests

on:
  push:
    branches:
      - main
      - dev/*

  pull_request:
    branches:
      - main
      - dev/*

jobs:
  call-tests:
    name: Extension tests
    uses: phpbb-extensions/test-framework/.github/workflows/tests.yml@3.3.x
    with:
      EXTNAME: mosparo/phpbbintegration
      RUN_MYSQL_JOBS: 0
      RUN_PGSQL_JOBS: 0
      RUN_MSSQL_JOBS: 0
      RUN_WINDOWS_JOBS: 0
      RUN_FUNCTIONAL_TESTS: 0
      PRIMARY_PHP_VERSION: '8.1'
      PHP_VERSION_MATRIX: '["8.1", "8.2", "8.3", "8.4"]'
      RUN_COMPOSER_INSTALL: 1